# Binh, Chapter 7 Homework
Problems 7.2.2d, 7.2.10d, 7.3.6c, 7.3.8c, 7.4.6c, 7.5.2d, 7.5.4d, 7.6.6d

In [1]:
# setup
from numpy import linalg as la
import numpy as np

## 7.2.2d & 7.2.10d
The problem(s) ask us to calculate the eigenvalues, eigenvectors, and the L2 norm of the provided matrix. We implement the calculations through python:

In [2]:
M1 = np.array([[3,2,-1],[1,-2,3],[2,0,4]])
eval1, evec1 = la.eig(M1)
print("The matrix's eigenvalues are", eval1)
print("The matrix's eigenvectors are \n", evec1)
norm1 = la.norm(M1)
print("The matrix's L2 norm is", norm1)

The matrix's eigenvalues are [ 3.  4. -2.]
The matrix's eigenvectors are 
 [[-4.08248290e-01 -1.81298661e-16  3.48742916e-01]
 [ 4.08248290e-01  4.47213595e-01 -9.29981110e-01]
 [ 8.16496581e-01  8.94427191e-01 -1.16247639e-01]]
The matrix's L2 norm is 6.928203230275509


## 7.3.6c & 7.3.8c

We are asked to solve a linear system using the provided algorithms. Since the implementations provided in the notebooks do not list tolerance, we would need to add a few details to both the Gauss Seidel method and the Jacobi method.

In [3]:
# first, declare the matrix/vector
M2 = np.array([[4,1,-1,1],[1,4,-1,-1],[-1,-1,5,1],[1,-1,1,3]])
b2 = np.array([-2,-1,0,1])
st2 = np.array([0,0,0,0])

# then, declare the helpers
def upper(A):
    n = len(A)
    U = np.zeros((n,n))
    for i in range(0,n):
        for j in range(i+1,n):
            U[i][j] = -A[i][j]
    return U

def lower(A):
    n = len(A)
    L = np.zeros((n,n))
    for i in range(0,n):
        for j in range(0,i):
            L[i][j] = -A[i][j]
    return L

def diag(A):
    n = len(A)
    D = np.zeros((n,n))
    for i in range(0,n):
        D[i][i] = A[i][i]
    return D

# the implementation with tolerance
def jacobi_iter(A,b,st,n,TOL):
    t = np.dot(la.inv(diag(A)),lower(A)+upper(A))
    c = np.dot(la.inv(diag(A)),b)
    vs = [st]
    v = st
    for i in range(0,n):
        v_old = v
        v = np.dot(t,v)+c
        vs.append(v)
        if la.norm(v - v_old, ord=np.inf) < TOL:
            return vs
    return 'Max number of iterations reached'

def gauss_seidel_iter(A,b,st,n, TOL):
    t = np.dot(la.inv(diag(A)-lower(A)),upper(A))
    c = np.dot(la.inv(diag(A)-lower(A)),b)
    vs = [st]
    v = st
    for i in range(0,n):
        v_old = v
        v = np.dot(t,v)+c
        vs.append(v)
        if la.norm(v - v_old, ord=np.inf) < TOL:
            return vs
    return 'Max number of iterations reached'

# now, solve the equations
J2 = jacobi_iter(M2,b2,st2,20,10**-3)
GS2 = gauss_seidel_iter(M2,b2,st2,10,10**-3)
print(J2, '\n', GS2)

[array([0, 0, 0, 0]), array([-0.5       , -0.25      ,  0.        ,  0.33333333]), array([-0.52083333, -0.04166667, -0.21666667,  0.41666667]), array([-0.64791667, -0.06979167, -0.19583333,  0.56527778]), array([-0.67282986,  0.00434028, -0.25659722,  0.59131944]), array([-0.71306424,  0.00188802, -0.25196181,  0.64458912]), array([-0.72460974,  0.02642289, -0.27115307,  0.65563802]), array([-0.73830349,  0.02727367, -0.27076497,  0.6740619 ]), array([-0.74302514,  0.0354001 , -0.27701834,  0.67878071]), array([-0.74779979,  0.03619688, -0.27728115,  0.68514786]), array([-0.74965647,  0.03891663, -0.27935016,  0.68709261]), array([-0.75133985,  0.03934973, -0.27956649,  0.68930775]), array([-0.75205599,  0.04027028, -0.28025957,  0.69008536])] 
 [array([0, 0, 0, 0]), array([-0.5  , -0.125, -0.125,  0.5  ]), array([-0.625     ,  0.        , -0.225     ,  0.61666667]), array([-0.71041667,  0.02552083, -0.2603125 ,  0.66541667]), array([-0.7378125 ,  0.03572917, -0.2735    ,  0.68234722])

From our experimentation, the Jacobi method did take more iterations to reach the required tolerance versus the Gauss-Seidel method.


## 7.4.6c
We are once again asked to solve a linear system, but this time using the SOR method. The provided implementation does not make use of tolerances, so appropriate changes will be added.

In [4]:
def sor(A,b,omega,st,n,TOL):
    t = np.dot(la.inv(diag(A)-omega*lower(A)),((1-omega)*diag(A)+omega*upper(A)))
    c = omega*np.dot(la.inv(diag(A)-omega*lower(A)),b)
    vs = [st]
    v = st
    for i in range(0,n):
        v_old = v
        v = np.dot(t,v)+c
        vs.append(v)
        if la.norm(v - v_old, ord=np.inf) < TOL:
            return vs
    return 'Max number of iterations reached'

M3 = np.array([[4,1,-1,1],[1,4,-1,-1],[-1,-1,5,1],[1,-1,1,3]])
b3 = np.array([-2,-1,0,1])
st3 = np.array([0,0,0,0])

sol3 = sor(M3,b3,1.2,st3,6,10**-3)
print(sol3)

[array([0, 0, 0, 0]), array([-0.6    , -0.12   , -0.1728 ,  0.66112]), array([-0.694176  ,  0.0787488 , -0.27181133,  0.68567045]), array([-0.77203397,  0.04001817, -0.28588244,  0.70203974]), array([-0.75397531,  0.04303615, -0.28193845,  0.69117202]), array([-0.75404892,  0.04037752, -0.28077473,  0.69184607]), array([-0.75308971,  0.04117281, -0.28074817,  0.69163506])]


## 7.5.2d & 7.5.4d
Using the provided matrix and the textbook definition, we can calculate the condition number:

In [5]:
M4 = np.array([[0.04, 0.01,-0.01],[0.2,0.5,-0.2],[1,2,4]])
M4I = la.inv(M4)
CN4 = la.norm(M4, ord = np.inf)*la.norm(M4I, ord = np.inf)
print("The matrix's condition number is", CN4)

The matrix's condition number is 198.17241379310343


Additionally, using the provided approximation, we can calculate the requested quantities:

In [6]:
x4 = np.array([1.827586,0.6551724,1.965517])
xt4 = np.array([1.8,0.64,1.9])
b4 = np.array([0.06,0.3,11])

e41 = la.norm(x4-xt4, ord = np.inf)
# making sure that the values agree
e42 = CN4 * ((la.norm((b4-np.dot(M4,xt4)).T, ord = np.inf)/la.norm(M4, ord = np.inf)))
print("The 2 requested values are", e41, 'and', e42)

The 2 requested values are 0.06551700000000005 and 9.059310344827594


## 7.6.6d
We are asked to implement the preconditioned conjugate gradient method to solve the same system of linear equations, with a provided preconditioning matrix.
For the implementation below, I assume that we are still working under the infinity norm (like the previous questions using the same system but requesting solutions through different methods). The number of iterations is also reduced to 2. Given the small number of iterations, the pre-set tolerance being the stopping condition is unlikely.


In [7]:
M5 = np.array([[4,1,-1,1],[1,4,-1,-1],[-1,-1,5,1],[1,-1,1,3]])
b5 = np.array([-2,-1,0,1])
st5 = np.array([0,0,0,0])

# the grad method implementation
def precon_grad(A, b, st, n, TOL):
    # since D^-1/2 is just a diagonal array, we might not need to use the entire matrix
    D = np.diag(A)
    Dsqrt = 1/np.sqrt(D)
    x = st
    r = b - np.dot(A, x)
    w = Dsqrt * r
    v = Dsqrt * w # since transpose of diag is the same
    alpha = np.dot(w,w)
    for _ in range(n):
        if la.norm(v, ord = np.inf) < TOL:
            return 'solution vector', x, 'with residual', r
        u = np.dot(A,v)
        t = alpha/np.dot(v,u)
        x = x + t*v
        r = r - t*u
        w = Dsqrt * r
        beta = np.dot(w,w)
        if np.abs(beta) < TOL:
            if la.norm(r, ord = np.inf) < TOL:
                return "solution vector", x, "with residual", r
        s = beta/alpha
        v = Dsqrt*w + s*v
        alpha = beta
    return "solution vector", x, "with residual", r

sol5 = precon_grad(M5, b5, st5, 2, 10**-3)
print(sol5)

('solution vector', array([-0.73729107, -0.04097673, -0.32454815,  0.59554923]), 'with residual', array([0.07004366, 0.17219909, 0.2489237 , 0.23421481]))
