# Binh, W6 Homework
6.3.6ac, 6.4.10, 6.5.10b, 6.6.6c, 6.6.12d, 6.6.16

In [6]:
# setup
import numpy as np
from matplotlib import pyplot as plt
import scipy as sp
import sympy as sym

## 6.3.6ac
To determine whether the matrices are (non)singular, we would need to calculate their determinants. Singular matrices will not be invertible. All of these calculations will be done in numpy/Python.

In [16]:
# first, we declare the matrices 
A6 = np.array([[1,2,-1],[0,1,2],[-1,4,3]])
C6 = np.array([[1,2,3,4],[2,1,-1,1],[-3,-2,0,1],[0,5,2,6]])

# then, we calculate the determinants 
DA6 = np.linalg.det(A6); DC6 = np.linalg.det(C6)
print("The determinants of the provided matrices are \n", DA6,DC6)

# both matrices are non-singular, so we calculate their inverses
A6I = np.linalg.inv(A6)
C6I = np.linalg.inv(C6)

print("The inverse of the provided matrices are \n", A6I,"\n" ,C6I)

The determinants of the provided matrices are 
 -10.000000000000002 -111.99999999999996
The inverse of the provided matrices are 
 [[ 0.5  1.  -0.5]
 [ 0.2 -0.2  0.2]
 [-0.1  0.6 -0.1]] 
 [[ 0.20535714  0.27678571 -0.08035714 -0.16964286]
 [-0.25       -0.25       -0.25        0.25      ]
 [ 0.27678571 -0.36607143 -0.15178571 -0.09821429]
 [ 0.11607143  0.33035714  0.25892857 -0.00892857]]


## 6.4.10
We need to declare the matrix printed out in the question. It would be reasonable to keep all of the matrix as operations on variables instead of directly calculating them:

In [20]:
# we first declare the function that would return the appropriate matrix given some vector and theta
def rotation_matrix(u, theta):
    u1, u2, u3 = u
    c = np.cos(theta)
    s = np.sin(theta)
    return np.array([
        [u1**2*(1-c)+c,u1*u2*(1-c) - u3*s,u1*u3*(1-c) + u2*s],
        [u1*u2*(1-c) + u3*s,u2**2*(1-c)+c,u2*u3*(1-c) - u1*s],
        [u1*u3*(1-c) - u2*s,u2*u3*(1-c)+u1*s,u3**2*(1-c)+ c]])

# now we use the relevant vectors:
R10 = rotation_matrix((np.sqrt(6)/6,np.sqrt(6)/3,np.sqrt(6)/6), np.pi/3)

# a, rotating the vector provided:
x10 = np.array([[1],[2],[3]])
a10 = np.dot(R10, x10)
print("a, The matrix that rotates the vector by 60 degrees about u is:\n", R10,
"\nApplying the matrix on x nets us: \n", a10)

# b, undoing the rotation:
R10I = np.linalg.inv(R10)
# testing to make sure the thing reverses:
b10 = np.dot(R10I, a10)
print("b, The matrix that undoes the rotation is \n", R10I, "\n","The result of applying the ~undoing~ matrix on the rotated vector is: \n", b10)

# c, calculating the determinants
det10 = np.linalg.det(R10)
det10I = np.linalg.det(R10I)
print("The determinants of these two matrices are:", det10, det10I)


a, The matrix that rotates the vector by 60 degrees about u is:
 [[ 0.58333333 -0.18688672  0.79044011]
 [ 0.52022006  0.83333333 -0.18688672]
 [-0.62377345  0.52022006  0.58333333]] 
Applying the matrix on x nets us: 
 [[2.58088023]
 [1.62622655]
 [2.16666667]]
b, The matrix that undoes the rotation is 
 [[ 0.58333333  0.52022006 -0.62377345]
 [-0.18688672  0.83333333  0.52022006]
 [ 0.79044011 -0.18688672  0.58333333]] 
 The result of applying the ~undoing~ matrix on the rotated vector is: 
 [[1.]
 [2.]
 [3.]]
The determinants of these two matrices are: 0.9999999999999998 1.0


d, Per the results that were printed out, we can make 2 observations:
- Aside from being able to calculate the matrix that undoes a rotation operation by a, switching the signs of the angle (from pi/3 to -pi/3) or calculating the inverse (through Gauss elimination), the inverse matrix of a rotation matrix is its transpose.
- Rotation matrices will have a determinant of 1.
This generalizes the results of questions b and c.

## 6.5.10b
Using the provided python code, we can carry out this factorization without much hassle:

In [23]:
A510 = np.array([[1,-2,3,0],[1,-2,3,1],[1,-2,2,-2],[2,1,3,1]])
# using the provided linalg.lu function from scipy
p,l,u = sp.linalg.lu(A510)
print(p)
print(l)
print(u)

[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
[[ 1.   0.   0.   0. ]
 [ 0.5  1.   0.   0. ]
 [ 0.5  1.   1.   0. ]
 [ 0.5  1.  -0.   1. ]]
[[ 2.   1.   3.   1. ]
 [ 0.  -2.5  1.5  0.5]
 [ 0.   0.  -1.  -3. ]
 [ 0.   0.   0.  -1. ]]


## 6.6.6c
Since we have been provided with a Cholesky implementation right in numpy.linalg, we will use that to factor our provided matrix:

In [28]:
A66 = np.array([[4,0,2,1],[0,3,-1,1],[2,-1,6,3],[1,1,3,8]])
L66 = np.linalg.cholesky(A66)
print("The LLt Decomposition of A is \n", L66, "\n", np.linalg.matrix_transpose(L66))

The LLt Decomposition of A is 
 [[ 2.          0.          0.          0.        ]
 [ 0.          1.73205081  0.          0.        ]
 [ 1.         -0.57735027  2.1602469   0.        ]
 [ 0.5         0.57735027  1.31157847  2.38671921]] 
 [[ 2.          0.          1.          0.5       ]
 [ 0.          1.73205081 -0.57735027  0.57735027]
 [ 0.          0.          2.1602469   1.31157847]
 [ 0.          0.          0.          2.38671921]]


Multiplying the two matrices together nets us:

In [26]:
np.dot(L66, np.linalg.matrix_transpose(L66))

array([[ 4.,  0.,  2.,  1.],
       [ 0.,  3., -1.,  1.],
       [ 2., -1.,  6.,  3.],
       [ 1.,  1.,  3.,  8.]])

which is the original matrix, as requested.

## 6.6.12d
We would need to implement the algorithm into python, then pass the matrix:

In [ ]:
def crout(n, A):
    # inefficient, but declare L and U as 0 matrices
    L = np.zeros((n, n))
    U = np.zeros((n, n))
    z = np.zeros(n) # intermediate
    x = np.zeros(n) # solution
    # filling the diagonal of upper, since it's all 1s
    np.fill_diagonal(U, 1)
    
    # declaring init
    L[0,0] = A[0,0]
    U[0,1] = A[0,1]/L[0,0]
    z[0] = A[0,n]/L[0,0]

    # loop for 1st step
    for i in range(1, n-1):
        L[i,i-1] = A[i, i-1]
        L[i,i] = A[i,i] - L[i,i-1]*U[i-1,i]
        U[i, i+1] = A[i, i+1] / L[i, i]
        z[i] = (A[i,n] - L[i,i-1]*z[i-1])/L[i,i]

    # declaring last vals:
    L[n-1,n-2] = A[n-1,n-2]
    L[n-1,n-1] = A[n-1,n-1] - L[n-1,n-2]*U[n-2,n-1]
    z[n-1] = (A[n-1,n] - L[n-1,n-2]*z[n-2])/L[n-1,n-1]
    x[n-1] = z[n-1]

    # x loop
    for i in range(n-2, -1, -1): # stepping back
        x[i] = z[i] - U[i,i+1]*x[i+1]

    return x

n = 5
A = np.array([
    [2, -1,  0,  0,  0,  1],
    [1,  2, -1,  0,  0,  2],
    [0,  2,  4, -1,  0, -1],
    [0,  0,  0,  2, -1, -2],
    [0,  0,  0,  1,  2, -1]])

# solution
print(crout(n, A))


[ 0.66666667  0.33333333 -0.66666667 -1.          0.        ]


## 6.6.16
For this assignment, it's reasonable to use the leading principal submatrix criterion to make sure that the matrix is positive definite. sympy's manipulation is very useful here:

In [8]:
# we are using a as the unknown
a = sym.Symbol('alpha')
A16 = sym.Matrix([
    [a,  1, -1],
    [1,  2,  1],
    [-1, 1,  4]
])

# leading principal submatrices
D1 = A16[:1, :1].det()
D2 = A16[:2, :2].det()
D3 = A16[:3, :3].det()
print(D1, "\n", D2, "\n", D3)

alpha 
 2*alpha - 1 
 7*alpha - 8


Having calculated each submatrix's determinant, we can now apply the criterion that all 3 of the expressions have to be positive. This means that the strictest inequality must hold, implying that $\alpha$ has to be $>8/7$ for the matrix to be positive definite.